# Generated by Django 5.2.1 on 2025-06-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_alternatif', models.CharField(help_text='Contoh: JRS atau KC', max_length=10, unique=True)),
                ('nama_alternatif', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alternatif',
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(help_text='Nama mata kuliah', max_length=100, unique=True)),
                ('bobot_jrs', models.FloatField(help_text='Bobot kriteria untuk fokus JRS (misal: 0.03, 0.08)')),
                ('bobot_kc', models.FloatField(help_text='Bobot kriteria untuk fokus KC (misal: 0.03, 0.08)')),
            ],
            options={
                'verbose_name_plural': 'Kriteria',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mahasiswa', models.CharField(blank=True, help_text='Nama (opsional)', max_length=150, null=True)),
                ('nim', models.CharField(blank=True, help_text='NIM (opsional)', max_length=20, null=True)),
                ('skor_final', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('rekomendasi_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekomendasi_jurusan.alternatif')),
            ],
            options={
                'verbose_name_plural': 'Data Sesi Mahasiswa (SPK)',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HasilRekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi_jurusan.alternatif')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_rekomendasi', to='rekomendasi_jurusan.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Hasil Perhitungan TOPSIS',
                'unique_together': {('mahasiswa', 'alternatif')},
            },
        ),
        migrations.CreateModel(
            name='NilaiMataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_mentah', models.FloatField(help_text='Nilai asli mahasiswa untuk mata kuliah ini (0-100)')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_matakuliah_spk', to='rekomendasi_jurusan.kriteria')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_matakuliah_spk', to='rekomendasi_jurusan.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Nilai Mata Kuliah (SPK)',
                'unique_together': {('mahasiswa', 'kriteria')},
            },
        ),
    ]
