# Generated by Django 5.2.1 on 2025-06-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi_jurusan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Data Sesi Mahasiswa (SPK)'},
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='rekomendasi_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekomendasi_jurusan.alternatif'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='skor_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='HasilRekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi_jurusan.alternatif')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_rekomendasi', to='rekomendasi_jurusan.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Hasil Perhitungan TOPSIS',
                'unique_together': {('mahasiswa', 'alternatif')},
            },
        ),
    ]
